// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listProjects: () => typedError<Project[], string>(__TAURI_INVOKE("list_projects")),
	getProject: (id: number) => typedError<{
	id: number,
	name: string,
	path: string,
	description: string,
	stack: string,
	architecture: string,
	dev_commands: string,
	test_commands: string,
	forbidden_tech: string,
	database_info: string,
	notes: string,
	created_at: string,
	updated_at: string,
} | null, string>(__TAURI_INVOKE("get_project", { id })),
	createProject: (input: NewProject) => typedError<Project, string>(__TAURI_INVOKE("create_project", { input })),
	updateProject: (id: number, input: ProjectUpdate) => typedError<Project, string>(__TAURI_INVOKE("update_project", { id, input })),
	deleteProject: (id: number) => typedError<null, string>(__TAURI_INVOKE("delete_project", { id })),
};

/* Types */
/**
 *  Campos aceitos ao criar um projeto. `path` já deve chegar validado/canonicalizado
 *  pela camada de commands (ver SECURITY-MODEL.md §3 — validação entra na Fase 3).
 */
export type NewProject = {
	name: string,
	path: string,
	description?: string,
	stack?: string,
	architecture?: string,
	dev_commands?: string,
	test_commands?: string,
	forbidden_tech?: string,
	database_info?: string,
	notes?: string,
};

export type Project = {
	id: number,
	name: string,
	path: string,
	description: string,
	stack: string,
	architecture: string,
	dev_commands: string,
	test_commands: string,
	forbidden_tech: string,
	database_info: string,
	notes: string,
	created_at: string,
	updated_at: string,
};

export type ProjectUpdate = {
	name: string,
	description: string,
	stack: string,
	architecture: string,
	dev_commands: string,
	test_commands: string,
	forbidden_tech: string,
	database_info: string,
	notes: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

