// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listProjects: () => typedError<Project[], string>(__TAURI_INVOKE("list_projects")),
	getProject: (id: number) => typedError<{
	id: number,
	name: string,
	path: string,
	description: string,
	stack: string,
	architecture: string,
	dev_commands: string,
	test_commands: string,
	forbidden_tech: string,
	database_info: string,
	notes: string,
	created_at: string,
	updated_at: string,
} | null, string>(__TAURI_INVOKE("get_project", { id })),
	/**
	 *  `input.path` chega como texto bruto do frontend — nunca confiar nele: valida e canonicaliza
	 *  (SECURITY-MODEL.md §3) antes de gravar, mesmo que a UI já tenha chamado `validate_project_path`
	 *  ou `preview_project_import` antes (defesa em profundidade, o backend nunca confia no frontend).
	 */
	createProject: (input: NewProject) => typedError<Project, string>(__TAURI_INVOKE("create_project", { input })),
	/**
	 *  `path` não é editável após a criação (ver `domain::ProjectUpdate` — não tem campo `path`),
	 *  então não há validação de caminho aqui.
	 */
	updateProject: (id: number, input: ProjectUpdate) => typedError<Project, string>(__TAURI_INVOKE("update_project", { id, input })),
	/**
	 *  Exclusão real (sem lixeira — SECURITY-MODEL.md §5); a UI exige confirmação antes de chamar.
	 *  `prompt_history.project_id` usa `ON DELETE SET NULL`, então o histórico não fica órfão.
	 */
	deleteProject: (id: number) => typedError<null, string>(__TAURI_INVOKE("delete_project", { id })),
	listProjectRules: (projectId: number) => typedError<ProjectRule[], string>(__TAURI_INVOKE("list_project_rules", { projectId })),
	createProjectRule: (input: NewProjectRule) => typedError<ProjectRule, string>(__TAURI_INVOKE("create_project_rule", { input })),
	updateProjectRule: (id: number, input: ProjectRuleUpdate) => typedError<ProjectRule, string>(__TAURI_INVOKE("update_project_rule", { id, input })),
	deleteProjectRule: (id: number) => typedError<null, string>(__TAURI_INVOKE("delete_project_rule", { id })),
	reorderProjectRules: (projectId: number, orderedIds: number[]) => typedError<null, string>(__TAURI_INVOKE("reorder_project_rules", { projectId, orderedIds })),
	/**
	 *  Valida e canonicaliza um caminho digitado pelo usuário, sem tocar no banco. Usado pelo
	 *  frontend pra dar feedback imediato (ex.: ao sair do campo de caminho) antes de tentar
	 *  importar ou salvar o projeto.
	 */
	validateProjectPath: (path: string) => typedError<string, string>(__TAURI_INVOKE("validate_project_path", { path })),
	/**
	 *  Importação assistida (SECURITY-MODEL.md §3): só lê arquivos da allowlist + lista nomes de
	 *  diretórios (2 níveis). Não salva nada — devolve um preview pra UI mostrar antes do usuário
	 *  confirmar. Só deve ser chamado sob ação explícita (botão "Pré-visualizar importação").
	 */
	previewProjectImport: (path: string) => typedError<ImportPreview, string>(__TAURI_INVOKE("preview_project_import", { path })),
	listAudioDevices: () => typedError<AudioDevice[], string>(__TAURI_INVOKE("list_audio_devices")),
	getRecordingSettings: () => typedError<RecordingSettings, string>(__TAURI_INVOKE("get_recording_settings")),
	saveRecordingSettings: (settings: RecordingSettings) => typedError<null, string>(__TAURI_INVOKE("save_recording_settings", { settings })),
	recordingStatus: () => typedError<RecordingStatus, string>(__TAURI_INVOKE("recording_status")),
	setActiveProject: (projectId: number | null) => typedError<null, string>(__TAURI_INVOKE("set_active_project", { projectId })),
	startRecording: () => typedError<null, string>(__TAURI_INVOKE("start_recording")),
	stopRecording: () => typedError<Recording, string>(__TAURI_INVOKE("stop_recording")),
	cancelRecording: () => typedError<null, string>(__TAURI_INVOKE("cancel_recording")),
	showRecorderWindow: () => typedError<null, string>(__TAURI_INVOKE("show_recorder_window")),
	/**  Esconde a janela compacta de gravação. Chamado pela própria janela ao terminar/cancelar. */
	hideRecorderWindow: () => typedError<null, string>(__TAURI_INVOKE("hide_recorder_window")),
	/**
	 *  Troca o atalho global em tempo real: desregistra o antigo, tenta o novo e, se o novo estiver
	 *  tomado por outro programa, **restaura o anterior** para o usuário não ficar sem atalho
	 *  nenhum por causa de uma escolha inválida.
	 */
	updateHotkey: (hotkeyCombo: string) => typedError<null, string>(__TAURI_INVOKE("update_hotkey", { hotkeyCombo })),
	listWhisperModels: () => typedError<WhisperModelOption[], string>(__TAURI_INVOKE("list_whisper_models")),
	/**  Status do motor para o modelo atualmente selecionado: pronto ou modelo ausente. */
	transcriptionStatus: () => typedError<EngineStatus, string>(__TAURI_INVOKE("transcription_status")),
	/**
	 *  Baixa o modelo selecionado, emitindo `model:download-progress` (0–100). Roda numa thread
	 *  dedicada porque o download é longo e não pode travar a UI; o resultado volta por evento
	 *  (`model:download-done` / `model:download-error`).
	 */
	downloadModel: () => typedError<null, string>(__TAURI_INVOKE("download_model")),
	/**
	 *  Transcreve a gravação `recording_id`: lê o WAV, roda o Whisper (com progresso via
	 *  `transcription:progress`), grava em `transcriptions`, apaga o WAV se `keep_audio` estiver
	 *  desligado, e atualiza o status da gravação. Retorna a transcrição salva.
	 * 
	 *  Roda numa thread (via spawn_blocking) porque o Whisper prende a CPU por segundos — travar o
	 *  worker do Tauri deixaria toda a UI sem resposta.
	 */
	transcribeRecording: (recordingId: number) => typedError<Transcription, string>(__TAURI_INVOKE("transcribe_recording", { recordingId })),
	listPromptModes: () => typedError<PromptModeOption[], string>(__TAURI_INVOKE("list_prompt_modes")),
	/**
	 *  `true` se o comando `claude` existe no PATH. A UI usa para avisar que a geração vai cair no
	 *  template antes mesmo de o usuário tentar.
	 */
	claudeCliAvailable: () => typedError<boolean, string>(__TAURI_INVOKE("claude_cli_available")),
	/**
	 *  Gera um prompt a partir de uma transcrição já salva e persiste o resultado.
	 * 
	 *  Roda em `spawn_blocking` porque o caminho do Claude CLI é um processo externo que pode
	 *  levar dezenas de segundos — travaria a UI se rodasse no worker do Tauri.
	 */
	generatePrompt: (transcriptionId: number, mode: PromptMode) => typedError<GenerationResult, string>(__TAURI_INVOKE("generate_prompt", { transcriptionId, mode })),
	/**
	 *  Refina um prompt existente (encurtar/detalhar/mais técnico/dividir em etapas).
	 * 
	 *  Sem o Claude CLI não há refino determinístico possível — o gerador devolve o prompt intacto
	 *  com um aviso, em vez de fingir que alterou.
	 */
	refinePrompt: (promptId: number, action: RefineAction) => typedError<GenerationResult, string>(__TAURI_INVOKE("refine_prompt", { promptId, action })),
	/**
	 *  Salva o texto editado pelo usuário (a edição livre é da Fase 7, mas o command já existe
	 *  para o editor consumir).
	 */
	updatePromptContent: (promptId: number, content: string) => typedError<GeneratedPrompt, string>(__TAURI_INVOKE("update_prompt_content", { promptId, content })),
};

/* Types */
export type AudioDevice = {
	name: string,
	/**
	 *  `true` para o microfone padrão do sistema — a UI marca ele como "(padrão)" e é o que
	 *  usamos quando o usuário nunca escolheu nada.
	 */
	is_default: boolean,
};

/**
 *  Estado do motor quanto ao modelo. A UI usa isso para decidir se precisa baixar antes de
 *  transcrever (ADR-001).
 */
export type EngineStatus = { status: "model_missing" } | { status: "downloading"; percent: number } | { status: "ready" };

/**
 *  Prompt gerado. `content` é a versão atual (pode ter sido editada pelo usuário na Fase 7);
 *  `original_content` guarda como saiu do gerador, para comparação/reversão.
 */
export type GeneratedPrompt = {
	id: number,
	transcription_id: number | null,
	project_id: number | null,
	/**  Valor de `PromptMode::as_db_str()`. */
	mode: string,
	/**  Valor de `PromptSource::as_db_str()` — `claude_cli` ou `template`. */
	generator: string,
	content: string,
	original_content: string,
	created_at: string,
	updated_at: string,
};

/**  Resultado da geração para a UI: o prompt salvo + aviso de fallback, se houve. */
export type GenerationResult = {
	prompt: GeneratedPrompt,
	/**  `Some` quando o Claude CLI falhou e o template foi usado — a UI mostra isso. */
	fallback_reason: string | null,
};

/**  Resultado da importação assistida: nada foi salvo, é só um preview do que *seria* lido. */
export type ImportPreview = {
	root: string,
	files: ImportedFile[],
	directories: string[],
};

/**  Um arquivo lido pela importação assistida (só arquivos da allowlist chegam aqui). */
export type ImportedFile = {
	relative_path: string,
	size_bytes: number,
	content: string,
};

/**
 *  Campos aceitos ao criar um projeto. `path` já deve chegar validado/canonicalizado
 *  pela camada de commands (ver SECURITY-MODEL.md §3 — validação entra na Fase 3).
 */
export type NewProject = {
	name: string,
	path: string,
	description?: string,
	stack?: string,
	architecture?: string,
	dev_commands?: string,
	test_commands?: string,
	forbidden_tech?: string,
	database_info?: string,
	notes?: string,
};

/**
 *  Nova regra: `sort_order` não é aceito do cliente — o repositório sempre acrescenta ao
 *  final da lista (maior `sort_order` do projeto + 1). Reordenar é uma operação à parte
 *  (`ProjectRuleRepo::reorder`).
 */
export type NewProjectRule = {
	project_id: number,
	rule: string,
};

export type Project = {
	id: number,
	name: string,
	path: string,
	description: string,
	stack: string,
	architecture: string,
	dev_commands: string,
	test_commands: string,
	forbidden_tech: string,
	database_info: string,
	notes: string,
	created_at: string,
	updated_at: string,
};

/**  Regra de projeto injetada no contexto do prompt (DATABASE-SCHEMA.md `project_rules`). */
export type ProjectRule = {
	id: number,
	project_id: number,
	rule: string,
	sort_order: number,
	created_at: string,
};

export type ProjectRuleUpdate = {
	rule: string,
};

export type ProjectUpdate = {
	name: string,
	description: string,
	stack: string,
	architecture: string,
	dev_commands: string,
	test_commands: string,
	forbidden_tech: string,
	database_info: string,
	notes: string,
};

/**
 *  Os 10 modos do gerador de prompts (PRODUCT-SPEC.md §5.4). A representação em banco é o
 *  `as_db_str()` — mantém o `CHECK` da coluna `mode` em `generated_prompts`/`prompt_history`.
 */
export type PromptMode = "clean_transcript" | "quick" | "technical" | "new_feature" | "bug_fix" | "refactor" | "planning" | "code_review" | "ui_creation" | "db_change";

export type PromptModeOption = {
	id: PromptMode,
	label: string,
	description: string,
};

export type RecorderState = "idle" | "recording" | "stopped" | "cancelled";

/**
 *  Metadados de uma gravação. `audio_path` é `None` depois que o WAV temporário é apagado
 *  (o caso normal — ver `RecordingRepo::clear_audio_path`).
 */
export type Recording = {
	id: number,
	project_id: number | null,
	duration_ms: number,
	device_name: string,
	audio_path: string | null,
	audio_kept: boolean,
	/**  `recorded` | `transcribing` | `transcribed` | `failed` | `cancelled` (CHECK no schema). */
	status: string,
	created_at: string,
};

export type RecordingSettings = {
	/**  `None` = usar o microfone padrão do sistema. */
	microphone: string | null,
	hotkey: string,
	/**  Manter o WAV após o processamento. **Desligado por padrão** (PRODUCT-SPEC §5.2). */
	keep_audio: boolean,
	/**
	 *  Id do modelo Whisper selecionado (ver `transcription::model_manager::MODELS`). Padrão
	 *  `large-v3-turbo` (ADR-001).
	 */
	whisper_model: string,
};

export type RecordingStatus = {
	state: RecorderState,
	elapsed_ms: number,
};

/**
 *  Ações de refino sobre um prompt já gerado (PRODUCT-SPEC §5.5). A Fase 7 (editor) as expõe
 *  na UI; a definição vive aqui porque quem as executa é o gerador.
 */
export type RefineAction = "shorten" | "expand" | "more_technical" | "split_into_steps";

export type Transcription = {
	id: number,
	recording_id: number,
	text: string,
	language: string,
	engine: string,
	model_name: string,
	/**  Tempo de processamento (ms), não a duração do áudio. */
	duration_ms: number,
	created_at: string,
};

export type WhisperModelOption = {
	id: string,
	label: string,
	downloaded: boolean,
	size_bytes: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

